// Generated metadata only: no book text.
(function(root){const catalog={
  "schemaVersion": 1,
  "recommendedBookId": "wizard-of-oz",
  "books": [
    {
      "schemaVersion": 1,
      "id": "wizard-of-oz",
      "title": "The Wonderful Wizard of Oz",
      "titleCN": "绿野仙踪",
      "author": "L. Frank Baum",
      "published": 1900,
      "language": "en",
      "genre": "Adventure",
      "readingStage": "Start here",
      "readingOrder": 1,
      "sectionType": "chapter",
      "sourceUrl": "https://www.gutenberg.org/ebooks/55",
      "license": "Project Gutenberg edition; retain the complete license in source.txt. Listed as public domain in the USA by the source.",
      "recommendation": "Start here: a concrete adventure with dialogue. Some vocabulary is old-fashioned.",
      "version": "305678c3ea998dcf",
      "sourceFile": "books/wizard-of-oz/source.txt",
      "sourceHash": "b0b430562073de8fc7b5d12d50b734b314534c87076e8143f4af8a5ba900e2f7",
      "wordCount": 39226,
      "sectionCount": 24,
      "manifestPath": "books/wizard-of-oz/manifest.json"
    },
    {
      "schemaVersion": 1,
      "id": "railway-children",
      "title": "The Railway Children",
      "titleCN": "铁路少年",
      "author": "E. Nesbit",
      "published": 1906,
      "language": "en",
      "genre": "Family",
      "readingStage": "Try next",
      "readingOrder": 2,
      "sectionType": "chapter",
      "sourceUrl": "https://www.gutenberg.org/ebooks/1874",
      "license": "Project Gutenberg edition; retain the complete license in source.txt. Listed as public domain in the USA by the source.",
      "recommendation": "Family life and conversations give you practical topics to retell and discuss.",
      "version": "55a8201d75e5d76a",
      "sourceFile": "books/railway-children/source.txt",
      "sourceHash": "d1f3a0bb583641c9d2e2ceffdc98b4f778708f800f0751ec52455b438149f452",
      "wordCount": 60017,
      "sectionCount": 14,
      "manifestPath": "books/railway-children/manifest.json"
    },
    {
      "schemaVersion": 1,
      "id": "secret-garden",
      "title": "The Secret Garden",
      "titleCN": "秘密花园",
      "author": "Frances Hodgson Burnett",
      "published": 1911,
      "language": "en",
      "genre": "Family & nature",
      "readingStage": "Early choice",
      "readingOrder": 3,
      "sectionType": "chapter",
      "sourceUrl": "https://www.gutenberg.org/ebooks/113",
      "license": "Project Gutenberg edition; retain the complete license in source.txt. Listed as public domain in the USA by the source.",
      "recommendation": "A clear story about feelings, friendship, and change. Some dialogue uses Yorkshire dialect.",
      "version": "64a1fa6ac9e1977d",
      "sourceFile": "books/secret-garden/source.txt",
      "sourceHash": "5400b33f2c137b5267411903056211d091895d9de65983b486e3f811a9fe75c0",
      "wordCount": 81084,
      "sectionCount": 27,
      "manifestPath": "books/secret-garden/manifest.json"
    },
    {
      "schemaVersion": 1,
      "id": "anne-of-green-gables",
      "title": "Anne of Green Gables",
      "titleCN": "绿山墙的安妮",
      "author": "L. M. Montgomery",
      "published": 1908,
      "language": "en",
      "genre": "Growing up",
      "readingStage": "Later step",
      "readingOrder": 4,
      "sectionType": "chapter",
      "sourceUrl": "https://www.gutenberg.org/ebooks/45",
      "license": "Project Gutenberg edition; retain the complete license in source.txt. Listed as public domain in the USA by the source.",
      "recommendation": "Richer descriptions and lively conversations about friendship and everyday life.",
      "version": "46e5d59b9630639a",
      "sourceFile": "books/anne-of-green-gables/source.txt",
      "sourceHash": "e80cb784a669cd6b3f71ed663aeb26cf4b2207225686ed8ab3567c52e663eda5",
      "wordCount": 103002,
      "sectionCount": 38,
      "manifestPath": "books/anne-of-green-gables/manifest.json"
    },
    {
      "schemaVersion": 1,
      "id": "sherlock-holmes",
      "title": "The Adventures of Sherlock Holmes",
      "titleCN": "福尔摩斯冒险史",
      "author": "Arthur Conan Doyle",
      "published": 1892,
      "language": "en",
      "genre": "Mystery",
      "readingStage": "Later challenge",
      "readingOrder": 5,
      "sectionType": "story",
      "sourceUrl": "https://www.gutenberg.org/ebooks/1661",
      "license": "Project Gutenberg edition; retain the complete license in source.txt. Listed as public domain in the USA by the source.",
      "recommendation": "Twelve separate mysteries: practise explaining events, clues, and your reasoning.",
      "version": "eb4b76595195be7a",
      "sourceFile": "books/sherlock-holmes/source.txt",
      "sourceHash": "51bf912e17919195e50cfa25458a6660ef35e00a5f44598b221196285c2220a5",
      "wordCount": 105143,
      "sectionCount": 12,
      "manifestPath": "books/sherlock-holmes/manifest.json"
    },
    {
      "schemaVersion": 1,
      "id": "great-gatsby",
      "title": "The Great Gatsby",
      "titleCN": "了不起的盖茨比",
      "author": "F. Scott Fitzgerald",
      "published": 1925,
      "language": "en",
      "genre": "Modern classic",
      "readingStage": "Early 20th-century English",
      "readingOrder": 6,
      "sectionType": "chapter",
      "sourceUrl": "https://www.gutenberg.org/ebooks/64317",
      "license": "Project Gutenberg edition; retain the complete license in source.txt. Listed as public domain in the USA by the source.",
      "recommendation": "1920s American English: parties, money and modern city life. Rich descriptions; read a chapter, then retell it.",
      "version": "bb2c99c752c5d253",
      "sourceFile": "books/great-gatsby/source.txt",
      "sourceHash": "0043e860b1091a2d3dbd7d186201258e05259f8ee44adc69b330264362b282b5",
      "wordCount": 48617,
      "sectionCount": 9,
      "manifestPath": "books/great-gatsby/manifest.json"
    },
    {
      "schemaVersion": 1,
      "id": "mysterious-affair-at-styles",
      "title": "The Mysterious Affair at Styles",
      "titleCN": "斯泰尔斯庄园奇案",
      "author": "Agatha Christie",
      "published": 1920,
      "language": "en",
      "genre": "Mystery",
      "readingStage": "Early 20th-century English",
      "readingOrder": 7,
      "sectionType": "chapter",
      "sourceUrl": "https://www.gutenberg.org/ebooks/863",
      "license": "Project Gutenberg edition; retain the complete license in source.txt. Listed as public domain in the USA by the source; it may still be under copyright in countries with life-plus-70-year terms.",
      "recommendation": "Agatha Christie's first Poirot mystery: lots of natural dialogue, questions and explanations — good for conversation English.",
      "version": "cdaf52f08e9ab47e",
      "sourceFile": "books/mysterious-affair-at-styles/source.txt",
      "sourceHash": "25a1dbefea6a51c6e1fb015e7a2bed3d7c43af74823ea92df5ec358e9bea07a3",
      "wordCount": 57101,
      "sectionCount": 13,
      "manifestPath": "books/mysterious-affair-at-styles/manifest.json"
    },
    {
      "schemaVersion": 1,
      "id": "the-conversation",
      "title": "The Conversation",
      "titleCN": "对话（每日新闻与评论）",
      "author": "University experts",
      "language": "en",
      "genre": "News & ideas",
      "readingStage": "Daily news",
      "readingOrder": 20,
      "sourceUrl": "https://theconversation.com/global",
      "license": "Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0). Article text is republished unchanged; images and embedded media are not included.",
      "licenseUrl": "https://creativecommons.org/licenses/by-nd/4.0/",
      "credit": "This article is republished from The Conversation under a Creative Commons license.",
      "recommendation": "New articles every day, written by university experts for general readers: current topics in natural, educated native English.",
      "sectionType": "article",
      "kind": "news",
      "version": "475dcc8322629579",
      "latestArticle": "2026-10-08T11:08:08Z",
      "wordCount": 31011,
      "sectionCount": 30,
      "manifestPath": "books/the-conversation/manifest.json"
    },
    {
      "schemaVersion": 1,
      "id": "voa-learning-english",
      "title": "VOA Learning English",
      "titleCN": "美国之音慢速英语",
      "author": "Voice of America",
      "language": "en",
      "genre": "Graded news & idioms",
      "readingStage": "Easier news",
      "readingOrder": 21,
      "sourceUrl": "https://learningenglish.voanews.com",
      "license": "Public domain (U.S. government work). Agency photos and other third-party material are not included.",
      "credit": "From VOA Learning English, a public-domain service of the Voice of America.",
      "recommendation": "Simpler, slower news English with audio and “Words in This Story” glossaries. An archive from early 2025: VOA stopped publishing new lessons in March 2025.",
      "sectionType": "article",
      "kind": "news",
      "version": "f41ee9196b8b0794",
      "latestArticle": "2025-03-20T22:05:17.000Z",
      "wordCount": 29190,
      "sectionCount": 41,
      "manifestPath": "books/voa-learning-english/manifest.json"
    }
  ]
}
;if(typeof module!=='undefined'&&module.exports)module.exports=catalog;else root.BookCatalog=catalog;})(typeof window!=='undefined'?window:globalThis);
